### PR TITLE
Restore original 1.3.0 commits

### PR DESCRIPTION
**Pull request by winterheart**
Before 1.3.0 got released there some commits left, namely XmlDecl and Charecter Data support.

### CODE REVIEW

**Comment by ConiKost** [comment]
@tomasguisasola ping

**Comment by Tieske** [comment]
This has been fixed, please use https://github.com/lunarmodules/luaexpat

This can be closed now

**Comment by winterheart** [comment]
@Tieske is that fork can be considered now official repository of luaexpat?

**Comment by Tieske** [comment]
yes

**Comment by Tieske** [comment]
see https://github.com/tomasguisasola/luaexpat/blob/master/README.md

**Comment by winterheart** [comment]
OK, thank you.

**Pull request closed without merging**
